// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plqodcvixngoocyvlqmb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBscW9kY3ZpeG5nb29jeXZscW1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQwMzE2MjQsImV4cCI6MjA5OTYwNzYyNH0.Xy32tKeePfs-eaRxbT561mTSK00HFvF2TMKeFr99EM8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});